### ISSUE TITLE
Cannot be GPL

### ISSUE THREAD

**Issue by Ronsor** [rd235/libslirp#1]
You cannot (correctly) license this under the GPL: slirp's old-style BSD license is incompatible with the GPL

**Comment by AkihiroSuda** [comment]
@Ronsor @rd235 
According to https://github.com/qemu/qemu/commit/2f5f89963186d42a7ded253bc6cf5b32abb45cec#diff-13b407282fe2c68dd10315c64e14c6c0 , 4-clause BSDL part seems to have been relicensed under 4-clause BSDL.

So, IIUC libslirp can be still under GPL.

However, whether it is under GPLv2 or GPLv2-or-later seems still unclear.

cc @cyphar

**Comment by AkihiroSuda** [comment]
@rd235 Is this issue closable?

**Comment by AkihiroSuda** [comment]
ping @rd235

**Comment by Ronsor** [comment]
This issue is solved.
